/**
 * 路由
 */
export const routers = {
  payload: [
    {
      id: 1128,
      tenantId: 'admin',
      deleted: null,
      createdBy: 'ANONYMOUS',
      createdTime: '2019-09-05 15:17:02',
      updatedBy: 'ANONYMOUS',
      updatedTime: '2019-09-05 15:25:40',
      elementResourceId: 226,
      functionGroupId: 317,
      parentId: 0,
      sort: 1,
      level: null,
      remark: null,
      idPath: '/1128/',
      appId: null,
      checkedStatus: null,
      keyword: null,
      name: '消息管理',
      code: 'message-management',
      description: null,
      type: 0,
      iconUrl: 'message-management',
      pathUrl: '/message-management',
      status: 0,
      enName: 'message-management',
      children: [
        {
          id: 1129,
          tenantId: 'admin',
          deleted: null,
          createdBy: 'ANONYMOUS',
          createdTime: '2019-09-05 15:21:32',
          updatedBy: 'ANONYMOUS',
          updatedTime: '2019-09-05 15:25:40',
          elementResourceId: 227,
          functionGroupId: 317,
          parentId: 1128,
          sort: 2,
          level: null,
          remark: null,
          idPath: '/1128/1129/',
          appId: null,
          checkedStatus: null,
          keyword: null,
          name: '短信',
          code: 'short-message',
          description: null,
          type: 0,
          iconUrl: '',
          pathUrl: '/message-management/short-message/template-management',
          status: 0,
          enName: 'short-message',
          children: [],
        },
        {
          id: 1130,
          tenantId: 'admin',
          deleted: null,
          createdBy: 'ANONYMOUS',
          createdTime: '2019-09-05 15:21:32',
          updatedBy: 'ANONYMOUS',
          updatedTime: '2019-09-05 15:25:40',
          elementResourceId: 228,
          functionGroupId: 317,
          parentId: 1128,
          sort: 3,
          level: null,
          remark: null,
          idPath: '/1128/1130/',
          appId: null,
          checkedStatus: null,
          keyword: null,
          name: '站内信',
          code: 'stand-inside-letter',
          description: null,
          type: 0,
          iconUrl: '',
          pathUrl: '/message-management/stand-inside-letter/event-management',
          status: 0,
          enName: 'stand-inside-letter',
          children: [],
        },
        {
          id: 1131,
          tenantId: 'admin',
          deleted: null,
          createdBy: 'ANONYMOUS',
          createdTime: '2019-09-05 15:21:32',
          updatedBy: 'ANONYMOUS',
          updatedTime: '2019-09-05 15:25:40',
          elementResourceId: 229,
          functionGroupId: 317,
          parentId: 1128,
          sort: 4,
          level: null,
          remark: null,
          idPath: '/1128/1131/',
          appId: null,
          checkedStatus: null,
          keyword: null,
          name: '邮箱',
          code: 'email',
          description: null,
          type: 0,
          iconUrl: '',
          pathUrl: '/message-management/email/event-management',
          status: 0,
          enName: 'email',
          children: [],
        },
      ],
    },
    {
      id: 1132,
      tenantId: 'admin',
      deleted: null,
      createdBy: 'ANONYMOUS',
      createdTime: '2019-09-05 15:25:40',
      updatedBy: 'ANONYMOUS',
      updatedTime: '2019-09-05 15:25:40',
      elementResourceId: 230,
      functionGroupId: 317,
      parentId: 0,
      sort: 5,
      level: null,
      remark: null,
      idPath: '/1132/',
      appId: null,
      checkedStatus: null,
      keyword: null,
      name: '接入管理',
      code: 'access-management',
      description: null,
      type: 0,
      iconUrl: 'access-management',
      pathUrl: '/access-management',
      status: 0,
      enName: 'access-management',
      children: [
        {
          id: 1133,
          tenantId: 'admin',
          deleted: null,
          createdBy: 'ANONYMOUS',
          createdTime: '2019-09-05 15:25:40',
          updatedBy: 'ANONYMOUS',
          updatedTime: '2019-09-05 15:25:40',
          elementResourceId: 231,
          functionGroupId: 317,
          parentId: 1132,
          sort: 6,
          level: null,
          remark: null,
          idPath: '/1132/1133/',
          appId: null,
          checkedStatus: null,
          keyword: null,
          name: '终端接入',
          code: 'terminal-access',
          description: null,
          type: 0,
          iconUrl: '',
          pathUrl: '/access-management/terminal-access',
          status: 0,
          enName: 'terminal-access',
          children: [],
        },
        {
          id: 1134,
          tenantId: 'admin',
          deleted: null,
          createdBy: 'ANONYMOUS',
          createdTime: '2019-09-05 15:25:40',
          updatedBy: 'ANONYMOUS',
          updatedTime: '2019-09-05 15:25:40',
          elementResourceId: 232,
          functionGroupId: 317,
          parentId: 1132,
          sort: 7,
          level: null,
          remark: null,
          idPath: '/1132/1134/',
          appId: null,
          checkedStatus: null,
          keyword: null,
          name: '短信服务商接入',
          code: 'short-message-service-provider',
          description: null,
          type: 0,
          iconUrl: '',
          pathUrl: '/access-management/short-message-service-provider',
          status: 0,
          enName: 'short-message-service-provider',
          children: [],
        },
        {
          id: 1135,
          tenantId: 'admin',
          deleted: null,
          createdBy: 'ANONYMOUS',
          createdTime: '2019-09-05 15:25:40',
          updatedBy: 'ANONYMOUS',
          updatedTime: '2019-09-05 15:25:40',
          elementResourceId: 233,
          functionGroupId: 317,
          parentId: 1132,
          sort: 8,
          level: null,
          remark: null,
          idPath: '/1132/1135/',
          appId: null,
          checkedStatus: null,
          keyword: null,
          name: '邮箱接入',
          code: 'email-access',
          description: null,
          type: 0,
          iconUrl: '',
          pathUrl: '/access-management/email-access',
          status: 0,
          enName: 'email-access',
          children: [],
        },
      ],
    },
  ],
};
// 用户信息
export const userInfo = {
  payload: {
    avatar: null,
    createdTime: '1568085156000',
    email: 'admin@deepexi.com',
    id: '81f9249f23b84a2c94d6eebd98c9a242',
    params: {nickname: 'admin', admin: true, userId: 0},
    admin: true,
    nickname: 'admin',
    userId: 0,
    phone: '13750492885',
    status: 0,
    tenantId: 'c1e419dfe8b944e0ba28967e9ce3ecda',
    token:
      'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY2NvdW50SWQiOiI4MWY5MjQ5ZjIzYjg0YTJjOTRkNmVlYmQ5OGM5YTI0MiIsInRlbmFudElkIjoiYzFlNDE5ZGZlOGI5NDRlMGJhMjg5NjdlOWNlM2VjZGEiLCJjaGFubmVsIjpudWxsLCJpc3MiOiJRdmFtY1dybFJ1OWlPWWljWm42Y1U0VXZHaHVRcTUySCIsInBhcmFtcyI6eyJuaWNrbmFtZSI6ImF5dSIsImFkbWluIjp0cnVlLCJ1c2VySWQiOjB9LCJleHAiOjE1Njg2MzgyNzIsImlhdCI6MTU2ODYzMTA3Mn0.i1_VxO2yArJFJvPYkWrDQnirbxFvHrcUsw1MAcbqKNY',
    username: 'admin',
  },
};

// 订阅信息
export const subscribeInfo = {
  payload: {
    content: [
      {
        productId: '1169507067011006559',
        productName: '消息中心',
        productUrl: 'xxx',
        status: 3,
        tenantId: 'c1e419dfe8b944e0ba28967e9ce3ecda',
      },
    ],
    number: 1,
    numberOfElements: 1,
    size: 1,
    totalElements: 1,
    totalPages: 1,
  },
};
